# Generated by Django 2.2.28 on 2023-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value12', models.UUIDField()),
                ('value13', models.EmailField(blank=True, max_length=200, null=True)),
                ('value14', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
