# Generated by Django 2.2.28 on 2023-05-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home10',
            name='value13',
        ),
    ]
